services:
  api:
    build: .
    working_dir: /app
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - APP_ENV=$APP_ENV
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - DATABASE_URL=$DATABASE_URL
    depends_on:
      - postgres

  postgres:
    image: pgvector/pgvector:pg15
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
